import os
f = open('popup.js', 'r', encoding='utf-8').read()

old_c = """function C(){const e=t()("#startAutoExtractModalBtn"),n=t()("#extractSpinnerModal");e.prop("disabled",!0),n.removeClass("d-none");const i=(i,r=!1)=>{chrome.tabs.sendMessage(i,{action:"startGroupScrape"});const s=()=>{chrome.storage.local.get(["LinksArray","ExtractError"],l=>{if(l.LinksArray){const s=new Date,c={title:"Auto Extracted - "+s.toLocaleDateString()+" "+s.toLocaleTimeString(),links:l.LinksArray};o.groups.push(c),B("groups",o.groups),chrome.storage.local.remove("LinksArray"),n.addClass("d-none"),e.prop("disabled",!1),M("Groups extracted and saved to collection successfully!","success",!0,"#alertContainerModal"),setTimeout(()=>{t()("#importGroupsModal").modal("hide"),r&&chrome.tabs.remove(i),a("groups")},2e3)}else l.ExtractError?(chrome.storage.local.remove("ExtractError"),n.addClass("d-none"),e.prop("disabled",!1),M("Error extracting groups: "+l.ExtractError,"danger",!0,"#alertContainerModal"),r&&chrome.tabs.remove(i)):setTimeout(s,1e3)})};s()};chrome.tabs.query({active:!0,currentWindow:!0},function(e){e.length>0&&e[0].url&&e[0].url.includes("facebook.com")?i(e[0].id,!1):(M("Creating a background Facebook process. Please wait...","info",!0,"#alertContainerModal"),chrome.tabs.create({url:"https://www.facebook.com/groups",active:!1},function(e){chrome.tabs.onUpdated.addListener(function t(n,o){n===e.id&&"complete"===o.status&&(chrome.tabs.onUpdated.removeListener(t),setTimeout(()=>{i(e.id,!0)},3e3))})}))})}"""
new_c = """function C(){const e=t()("#startAutoExtractModalBtn"),n=t()("#extractSpinnerModal");e.prop("disabled",!0),n.removeClass("d-none");const i=(i,r=!1)=>{chrome.tabs.sendMessage(i,{action:"startGroupScrape"});const s=()=>{chrome.storage.local.get(["LinksArray","ExtractError"],l=>{if(l.LinksArray){l.LinksArray.forEach(e=>w(e)),chrome.storage.local.remove("LinksArray"),n.addClass("d-none"),e.prop("disabled",!1),M("Groups extracted and added to list!","success",!0,"#alertContainerModal"),r&&chrome.tabs.remove(i)}else l.ExtractError?(chrome.storage.local.remove("ExtractError"),n.addClass("d-none"),e.prop("disabled",!1),M("Error extracting groups: "+l.ExtractError,"danger",!0,"#alertContainerModal"),r&&chrome.tabs.remove(i)):setTimeout(s,1e3)})};s()};chrome.tabs.query({active:!0,currentWindow:!0},function(e){e.length>0&&e[0].url&&e[0].url.includes("facebook.com")?i(e[0].id,!1):(M("Creating a background Facebook process. Please wait...","info",!0,"#alertContainerModal"),chrome.tabs.create({url:"https://www.facebook.com/groups",active:!1},function(e){chrome.tabs.onUpdated.addListener(function t(n,o){n===e.id&&"complete"===o.status&&(chrome.tabs.onUpdated.removeListener(t),setTimeout(()=>{i(e.id,!0)},3e3))})}))})}"""

old_e = """function E(){const e=document.getElementById("csvFileInput"),n=e.files[0];if(!n)return void M("Please select a CSV file first.","warning",!0,"#alertContainerModal");const i=new FileReader;i.onload=function(n){const i=n.target.result.split(/\r?\n/),r=[];let s=0;for(let e of i)e=e.trim(),e&&(e.includes("facebook.com/groups/")?r.push(e):s++);if(0===r.length)return void M("No valid Facebook group links found in the CSV. (URLs must contain 'facebook.com/groups/')","danger",!0,"#alertContainerModal");const l=new Date,c={title:"Imported CSV - "+l.toLocaleDateString()+" "+l.toLocaleTimeString(),links:r};o.groups.push(c),B("groups",o.groups);let u=`${r.length} groups imported successfully!`;s>0&&(u+=` ${s} invalid rows were skipped.`),M(u,"info",!0,"#alertContainerModal"),e.value="",setTimeout(()=>{t()("#importGroupsModal").modal("hide"),a("groups")},2e3)},i.readAsText(n)}"""
new_e = """function E(){const e=document.getElementById("csvFileInput"),n=e.files[0];if(!n)return void M("Please select a CSV file first.","warning",!0,"#alertContainerModal");const i=new FileReader;i.onload=function(n){const i=n.target.result.split(/\r?\n/),r=[];let s=0;for(let e of i)e=e.trim(),e&&(e.includes("facebook.com/groups/")?r.push(e):s++);if(0===r.length)return void M("No valid Facebook group links found in the CSV. (URLs must contain 'facebook.com/groups/')","danger",!0,"#alertContainerModal");r.forEach(e=>w(e));let u=`${r.length} groups imported successfully!`;s>0&&(u+=` ${s} invalid rows were skipped.`),M(u,"info",!0,"#alertContainerModal"),e.value=""},i.readAsText(n)}"""

f2 = f.replace(old_c, new_c).replace(old_e, new_e)
if old_c in f and old_e in f:
    open('popup.js', 'w', encoding='utf-8').write(f2)
    print('Patched successfully')
else:
    print('Failed to find C or E in popup.js')
    if old_c not in f:
        print('C not found')
    if old_e not in f:
        print('E not found')
